config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # get 'users/new'

  get '/signup' => 'users#new'
  get '/users' => 'users#index'

  post '/users' => 'users#create'

  resources :giphies
  root 'welcome#index'

  resources :giphy
  resources :save
  # get 'dupa' => 'giphy#lalala', as: :hello
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/giphy.rb
class Giphy < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :giphies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to login_path unless current_user
  end
end

app/controllers/giphies_controller.rb
# class GiphiesController < ApplicationController
#   before_action :set_giphy, only: [:show, :edit, :update, :destroy]

#   # GET /giphies
#   # GET /giphies.json
#   def index
#     @giphies = Giphy.all
#   end

#   # GET /giphies/1
#   # GET /giphies/1.json
#   def show
#   end

#   # GET /giphies/new
#   def new
#     @giphy = Giphy.new
#   end

#   # GET /giphies/1/edit
#   def edit
#   end

#   # POST /giphies
#   # POST /giphies.json
#   def create
#     @giphy = Giphy.new(giphy_params)

#     respond_to do |format|
#       if @giphy.save
#         format.html { redirect_to @giphy, notice: 'Giphy was successfully created.' }
#         format.json { render :show, status: :created, location: @giphy }
#       else
#         format.html { render :new }
#         format.json { render json: @giphy.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /giphies/1
#   # PATCH/PUT /giphies/1.json
#   def update
#     respond_to do |format|
#       if @giphy.update(giphy_params)
#         format.html { redirect_to @giphy, notice: 'Giphy was successfully updated.' }
#         format.json { render :show, status: :ok, location: @giphy }
#       else
#         format.html { render :edit }
#         format.json { render json: @giphy.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /giphies/1
#   # DELETE /giphies/1.json
#   def destroy
#     @giphy.destroy
#     respond_to do |format|
#       format.html { redirect_to giphies_url, notice: 'Giphy was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_giphy
#       @giphy = Giphy.find(params[:id])
#     end

#     # Never trust parameters from the scary internet, only allow the white list through.
#     def giphy_params
#       params.require(:giphy).permit(:image, :title)
#     end
# end

app/controllers/giphy_controller.rb
class GiphyController < ApplicationController

  protect_from_forgery unless: -> { request.format.json? }

  BASE_URL = "http://api.giphy.com/v1/gifs/search"
  # SEARCHED_GIPH = "api_key=#{ENV['GIPHY_API_KEY']}"

  def response_from_giphy(input, number)
    request = HTTParty.get(BASE_URL, query: search_format(input, number)).to_json
    response_hash = JSON.parse(request)
    # p search_format.to_query
    # p response_hash
    response_hash["data"].map { |ele| ele }
  end

  def search_format(input, number)
    {
      q: input,
      api_key: ENV['GIPHY_API_KEY'],
      limit: number
    }
  end

  def create
    render json: response_from_giphy(params[:input], params[:number])
  end

  # def show
  #   @user_search_input = params[:q]
  #   @user_limit_input = params[:number]
  #   @response = response_from_giphy
  #   @gifs = @response
  #   # override defoult action which is looking for a view
  #   render json: { gifs: @gifs }
  # end

  def post_dada
    respond_to do |format|
      format.json { render json: query }
    end
  end


end

app/controllers/save_controller.rb
class SaveController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    authenticate_user!
    @giphies = current_user.giphies
  end

  def create
    authenticate_user!
    @giphy = Giphy.new(params.permit(:image, :title, :created_at))
    @giphy.user_id = current_user.id

    respond_to do |format|
      if @giphy.save
        format.html { redirect_to @giphy, notice: "Giphy was successfully saved!" }
        format.json { render :show }
      else
        format.html { render :new }
        format.json { render json: @giphy.errors, status: :unprocessable_entity }
      end
    end
    # binding.pry
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email:login_params[:email])
    if user && user.authenticate(login_params[:password])
        session[:user_id] = user.id
        flash[:success] = "Seccesfully logged in!"
        redirect_to root_path
    else
        flash[:warning] = ['invalid credentials']
        redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = "Succesfully logged out!"
    redirect_to login_path
  end

  private
  def login_params
    params.require(:login).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user
      @users = User.all
      render 'index.html.erb'
    else
      flash[:warning] = "You must be logged in"
      redirect_to login_path
    end
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:register_errors] = user.errors.full_messages
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/giphies_helper.rb
module GiphiesHelper
end

app/helpers/giphy_helper.rb
module GiphyHelper
end

app/helpers/save_helper.rb
module SaveHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/giphies/_form.html.erb
<%= form_with(model: giphy, local: true) do |form| %>
  <% if giphy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(giphy.errors.count, "error") %> prohibited this giphy from being saved:</h2>

      <ul>
      <% giphy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/giphies/edit.html.erb
<h1>Editing Giphy</h1>

<%= render 'form', giphy: @giphy %>

<%= link_to 'Show', @giphy %> |
<%= link_to 'Back', giphies_path %>

app/views/giphies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Giphies</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @giphies.each do |giphy| %>
      <tr>
        <td><%= giphy.image %></td>
        <td><%= giphy.title %></td>
        <td><%= link_to 'Show', giphy %></td>
        <td><%= link_to 'Edit', edit_giphy_path(giphy) %></td>
        <td><%= link_to 'Destroy', giphy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Giphy', new_giphy_path %>

app/views/giphies/new.html.erb
<h1>New Giphy</h1>

<%= render 'form', giphy: @giphy %>

<%= link_to 'Back', giphies_path %>

app/views/giphies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @giphy.image %>
</p>

<p>
  <strong>Title:</strong>
  <%= @giphy.title %>
</p>

<%= link_to 'Edit', edit_giphy_path(@giphy) %> |
<%= link_to 'Back', giphies_path %>

app/views/giphy/_result.html.erb
<section>
  <div id="giphy_results">
  </div>
  <div class="left-arrow"><%= image_tag("arrow.png") %></div>
  <div class="right-arrow"><%= image_tag("arrow.png") %></div>
</section>

<script id="myTemplate" type="text/html">

  {{ names.forEach(function (name) { }}
  <h1>{{= name }}</h1>
  {{ }) }}

  {{ images.forEach(function (image) { }}
    <video autoplay loop>
      <source
        src="{{= image.img }}"
        type="video/mp4"
        data-title="{{= image.title}}"
        id="{{= image.id }}">
    </video>
  {{ }) }}

</script>

app/views/giphy/index.html.erb
<div class="giphy_form">
  <%= form_tag("/hello", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:number) %>
    <%= submit_tag("Search") %>
  <% end %>
</div>

app/views/giphy/show.html.erb
# <% @gifs.each do |gif| %>
#   <h2><%= gif %></h2>
# <% end %>

app/views/giphy/whatever.erb
<% @gifs.each do |gif| %>
  <img src="#{gif}">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiphyPage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render "giphy/result" %>
  </body>
</html>

app/views/save/index.html.erb
<% if @giphies.any? %>
  <% @giphies.each do |giphy| %>
    <h1><%= giphy.title %></h1>
  <% end %>
<% else %>
  <h1>No giphes :(</h1>
<% end %>

app/views/users/index.html.erb
<% if @users.any? %>
  <% @users.each do |user| %>
    <h1><%= user.name %></h1>
  <% end %>
<% else %>
  <h1>No users!!!</h1>
<% end %>

app/views/users/new.html.erb
<h1>
  Registration
</h1>

<form action='/users' method='POST'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
    <input type="name" name="user[name]" placeholder="name">
    <input type="email" name="user[email]" placeholder="email">
    <input type="password" name="user[password]" placeholder="password">
    <input type="submit" name="submit" class="submit">
</form>

app/views/users/show.html.erb
<h1>User <%= @User.name %></h1>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<h2>Find your favourite giphy!</h2>

<div>
  <%= link_to('search for GIPHY', giphy_index_path) %>
</div>
<div>
  <%= link_to('Register', signup_path) %>
</div>